Backend/M5/BW/Team-5/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Models.ViewModels;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "VetPolicy")]
    public class AnimalsController : Controller
    {
        private readonly IAnimalsService _animalsSvc;
        private readonly IBreedsService _breedSvc;

        public AnimalsController(IAnimalsService animalsService, IBreedsService breedsService)
        {
            _animalsSvc = animalsService;
            _breedSvc = breedsService;
        }

        [HttpGet]

        public async Task<IActionResult> CreateAnimal()
        {
            var viewModel = await _animalsSvc.GetCreateAnimalViewModelAsync();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateAnimal(CreateAnimalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var animal = await _animalsSvc.CreateAnimalAsync(viewModel);
                    return RedirectToAction("AnimalList");
                }
                catch (ArgumentException ex)
                {
                    ModelState.AddModelError("", ex.Message);
                }
            }

            viewModel.Breeds = await _breedSvc.GetAllBreedsAsync();
            return View(viewModel);
        }

        public async Task<IActionResult> AnimalList()
        {
            var animals = await _animalsSvc.GetAllAnimalsAsync();
            return View(animals);
        }

        public IActionResult GetAnimalByMicrochip()
        {
            return View();
        }


        [HttpGet("Animals/GetAnimalDataByMicrochip")]
        public async Task<IActionResult> GetAnimalDataByMicrochip(string microchipId)
        {
            var animals = await _animalsSvc.GetAnimalByMicrochipAsync(microchipId);
            var animalData = animals.Select(animal => new
            {
                animal.Name,
                RegistrationDate = animal.RegistrationDate.ToString("yyyy-MM-dd"),
                BirthDate = animal.BirthDate.ToString("yyyy-MM-dd"),
                animal.Color,
                Image = animal.Image != null ? Convert.ToBase64String(animal.Image) : null,
                IsHospitalized = animal.Hospitalization != null && animal.Hospitalization.Any(h => h.IsHospitalized)
            }).ToList();

            return Ok(animalData);
        }


        public async Task<IActionResult> AnimalsWithoutOwner()
        {
            var animals = await _animalsSvc.GetAnimalsWithoutOwnerAsync();
            return View(animals);
        }

        // eliminazione animale

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAnimal(int id)
        {
            var success = await _animalsSvc.DeleteAnimalAsync(id);
            if (!success)
            {
                return NotFound();
            }

            return RedirectToAction("AnimalList");
        }
    }
}

Backend/M5/BW/Team-5/Controllers/MasterController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Models.Auth;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "MasterPolicy")]
    public class MasterController : Controller
    {
        private readonly IMasterService _masterSvc;

        public MasterController(IMasterService masterService)
        {
            _masterSvc = masterService;
        }

        public async Task<IActionResult> ManageRoles()
        {
            ViewBag.Users = await _masterSvc.GetAllUsersWithRolesAsync();
            ViewBag.Roles = await _masterSvc.GetAllRolesAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ManageRoles(int idUser, int idRole)
        {
            await _masterSvc.ToggleUserRoleAsync(idUser, idRole);
            return RedirectToAction("ManageRoles");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRole(Roles role)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Users = await _masterSvc.GetAllUsersWithRolesAsync();
                ViewBag.Roles = await _masterSvc.GetAllRolesAsync();

                return View("ManageRoles");
            }

            try
            {
                await _masterSvc.CreateRoleAsync(role);
                return RedirectToAction("ManageRoles");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("CrRole", ex.Message);
                return View("ManageRoles");
            }
        }
    }
}

Backend/M5/BW/Team-5/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Context;
using Team_5.Models.Pharmacy;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "FarmacPolicy")]
    public class OrdersController : Controller
    {
        private readonly IOrdersService _ordersSvc;
        private readonly DataContext _ctx;

        public OrdersController(IOrdersService ordersService, DataContext dataContext)
        {
            _ordersSvc = ordersService;
            _ctx = dataContext;
        }

        public async Task<IActionResult> CreateOrder()
        {
            ViewBag.Products = await _ordersSvc.GetAllProducts();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> CreateOrder(Orders o, string cf)
        {
            var order = await _ordersSvc.CreateOrder(o, cf);

            if (order == null)
            {
                ModelState.AddModelError(string.Empty, "Il codice fiscale o il prodotto fornito non sono validi.");
                ViewBag.Products = await _ordersSvc.GetAllProducts();
                return View(o);
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<ActionResult<List<Orders>>> OrderList()
        {
            var orderList = await _ordersSvc.GetOrders();
            return View(orderList);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteOrder(int id)
        {
            var deletedOrder = await _ordersSvc.DeleteOrders(id);

            if (deletedOrder == null)
            {
                // Se l'ordine non esiste, restituisci un 404 Not Found
                return NotFound(new { Message = "Order not found." });
            }

            return RedirectToAction("OrderList");
        }
    }
}

Backend/M5/BW/Team-5/Controllers/OwnersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Team_5.Models.ViewModels;
using Team_5.Services.Interfaces;

namespace Team_5.Controllers
{
    [Authorize(Policy = "VetPolicy")]
    public class OwnersController : Controller
    {
        private readonly IOwnersService _ownersService;

        public OwnersController(IOwnersService ownersService)
        {
            _ownersService = ownersService;

        }

        [HttpGet]
        public async Task<IActionResult> CreateOwner()
        {
            ViewBag.Users = await _ownersService.GetAllUsers();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOwner(OwnerViewModel ow)
        {
            await _ownersService.CreateOwnersAsync(ow);
            return RedirectToAction("OwnersList");
        }


        [HttpGet]
        public async Task<IActionResult> OwnersList()
        {
            var owners = await _ownersService.GetAllOwnersAsync();
            return View(owners);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOwner(int id)
        {
            await _ownersService.DeleteOwner(id);
            return RedirectToAction("OwnersList");
        }
    }
}

Backend/M5/BW/Team-5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Team_5</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />

</head>
<body class="overflow-hidden myBlack">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 p-0">
                <nav class="navbar navbar-expand myBg sticky-top px-4 py-0">
                    <div class="navbar-nav align-items-center flex-grow-1 justify-content-between px-4 py-2">
                        <li>
                            <a class="text-white mt-5 fs-4" asp-area="" asp-controller="Home" asp-action="Index">

                                <i class="bi bi-house-door myIcon fs-2"></i>
                            </a>
                        </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                <a class="fs-2" asp-area="" asp-controller="Auth" asp-action="Logout">
                                    <i class="bi bi-door-closed myIcon"></i>
                                </a>
                                </li>
                            }
                            @if (!User.Identity.IsAuthenticated)
                            {
                               
                                <li class="nav-item">
                                    <a class="fs-2" asp-area="" asp-controller="Auth" asp-action="Login">
                                        <i class="bi bi-door-closed-fill myIcon"></i>
                                    </a>
                                </li>
                            }
                    </div>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2 myBg" id="scrollStyle">
                @if (!User.Identity.IsAuthenticated)
                {
                    <h2 class="text-white text-center">I NOSTRI SOCIAL</h2>
        <div class="d-flex flex-column align-items-center">
          <div class="mt-2">
            <a
              href="https://www.youtube.com/watch?v=A4StMUgtAJc"
              target="_blank" class="display-5"
            >
              <i class="bi bi-facebook myIcon"></i>
          </div>
          <div class="mt-3">
            <a
              href="https://www.youtube.com/watch?v=bFvqf8Z13PU"
              target="_blank" class="display-5"
            >
              <i class="bi bi-instagram myIcon"></i>
            </a>
          </div>
           <div class="mt-3">
            <a
              href="https://www.youtube.com/watch?v=kE3-JAo0VQc"
              target="_blank" class="display-5"
            >
              <i class="fa-brands fa-threads myIcon"></i>
            </a>
          </div>
          <div class="mt-3">
            <a
              href="https://www.youtube.com/watch?v=dW2utwg9oOg"
              target="_blank" class="display-5"
            >
               <i class="fa-brands fa-x-twitter myIcon"></i>
            </a>
          </div>
          <div class="mt-3">
            <a
              href="https://www.youtube.com/watch?v=tzJdk9g0gG0"
              target="_blank" class="display-5"
            >
              <i class="bi bi-youtube myIcon"></i>
            </a>
          </div>
          <div class="mt-3">
            <a
              href="https://www.youtube.com/watch?v=G0hLIqWpJpQ"
              target="_blank" class="display-5"
            >
              <i class="bi bi-tiktok myIcon"></i>
            </a>
          </div>
        </div>
                }
                <ul class="list-unstyled ps-3 pb-4">

                    @if (User.IsInRole("veterinario"))
                    {
                        <li class="text-white  my-2">PROPRIETARI</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Owners" asp-action="CreateOwner">Registra Proprietario</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Owners" asp-action="OwnersList">Lista Proprietari</a>
                        </li>

                        <li class="text-white mt-5 mb-2">ANIMALI</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Animals" asp-action="CreateAnimal">Registra Animale</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Animals" asp-action="AnimalList">Lista Animali</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Animals" asp-action="AnimalsWithoutOwner">Lista Animali Senza Padrone</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Animals" asp-action="GetAnimalByMicrochip">Cerca Animale Per Microchip</a>
                        </li>

                        <li class="text-white mt-5 mb-2">VISITE</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Examination" asp-action="CreateExamination">Registra Visita</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-controller="Examination" asp-action="ExaminationsList">Lista Visite</a>
                        </li>

                        <li class="text-white mt-5 mb-2">RICOVERI</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Hospitalization" asp-action="CreateHospitalization">Registra Ricovero</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Hospitalization" asp-action="CreateAnimalAndHospitalization">Registrazione Ricovero nuovo Animale</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Hospitalization" asp-action="ActiveHospitalizations">Lista Ricoveri Attivi</a>
                        </li>

                    }
                    @if (User.IsInRole("farmacista"))
                    {
                        <li class="text-white mt-5 mb-2">PRODOTTI</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Product" asp-action="CreateProduct">Registra Prodotto</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Product" asp-action="ProductList">Lista Prodotti</a>
                        </li>

                        <li class="text-white mt-5 mb-2">ORDINI</li>

                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Orders" asp-action="CreateOrder">Registra Ordine</a>
                        </li>
                        <li class="nav-item">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Orders" asp-action="OrderList">Lista Ordini</a>
                        </li>

                    }
                    @if (User.IsInRole("master"))
                    {
                        <li class="text-white mt-5 mb-2">RUOLI</li
                        <li class="nav-item mt-5 mb-5">
                            <a class="fs-5 mylink" asp-area="" asp-controller="Master" asp-action="ManageRoles">Gestisci Ruoli</a>
                        </li>
                    }
                </ul>
            </div>

            <div class="col-10 p-0" id="scrollStyleTwo">
                
                <main role="main" class="py-5 container-fluid">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>